// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Society.Infrastructure.Data;

#nullable disable

namespace Society.Infrastructure.Migrations
{
    [DbContext(typeof(SocietyDbContext))]
    [Migration("20260212022903_InitDatabase")]
    partial class InitDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Society.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("Society.Domain.Entities.Program", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Programs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Information Technology Engineering"
                        });
                });

            modelBuilder.Entity("Society.Domain.Entities.ProgramSubject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("ProgramId", "SubjectId")
                        .IsUnique();

                    b.ToTable("ProgramSubjects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9b8e70b7-8561-467f-bdb5-f88ecc23feab"),
                            ProgramId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SubjectId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("fe82ce59-0cd4-4b86-b12d-81397508b1d5"),
                            ProgramId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SubjectId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("45f449cc-1d36-47c7-9252-272214e68904"),
                            ProgramId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SubjectId = new Guid("20000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("dc2d091f-5088-4067-b053-cf5b9cffb396"),
                            ProgramId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SubjectId = new Guid("20000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("54a5b878-f801-4023-b2c4-f2384c34b592"),
                            ProgramId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SubjectId = new Guid("20000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("49b182a5-a099-47f4-b3e8-3e18f02f728e"),
                            ProgramId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SubjectId = new Guid("20000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("b21bb3c7-2869-46d5-a7fb-7f97a8a82c99"),
                            ProgramId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SubjectId = new Guid("20000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("e8af1649-309f-4aba-a7f3-3aef954ac753"),
                            ProgramId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SubjectId = new Guid("20000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("83aedf3c-7601-43f9-9d78-b57b784174b4"),
                            ProgramId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SubjectId = new Guid("20000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("c8497aba-6cf8-4939-90d2-c51877620c8e"),
                            ProgramId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SubjectId = new Guid("20000000-0000-0000-0000-000000000010")
                        });
                });

            modelBuilder.Entity("Society.Domain.Entities.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Code = "BPG401",
                            Name = "Web Programming 1"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            Code = "BPG402",
                            Name = "Web Programming 2"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            Code = "DBS301",
                            Name = "Databases"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            Code = "ALG201",
                            Name = "Algorithms"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            Code = "OOP101",
                            Name = "OOP"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000006"),
                            Code = "NET101",
                            Name = "Networking"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000007"),
                            Code = "SEC201",
                            Name = "Cyber Security"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000008"),
                            Code = "AI101",
                            Name = "Intro to AI"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000009"),
                            Code = "SE201",
                            Name = "Software Engineering"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000010"),
                            Code = "OS301",
                            Name = "Operating Systems"
                        });
                });

            modelBuilder.Entity("Society.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FormationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProgramSubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("FormationId")
                        .IsUnique();

                    b.HasIndex("ProgramSubjectId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Society.Domain.Entities.TeamFormation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentMembersCount")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("MaxMembers")
                        .HasColumnType("int");

                    b.Property<Guid>("ProgramSubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProgramSubjectId");

                    b.HasIndex("Status");

                    b.ToTable("TeamFormations");
                });

            modelBuilder.Entity("Society.Domain.Entities.TeamMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("TeamId", "UserId")
                        .IsUnique();

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("Society.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Society.Domain.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Faculty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Major")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("University")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("Society.Domain.Entities.ProgramSubject", b =>
                {
                    b.HasOne("Society.Domain.Entities.Program", "Program")
                        .WithMany("ProgramSubjects")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Society.Domain.Entities.Subject", "Subject")
                        .WithMany("ProgramSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Program");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Society.Domain.Entities.Team", b =>
                {
                    b.HasOne("Society.Domain.Entities.TeamFormation", "Formation")
                        .WithOne("Team")
                        .HasForeignKey("Society.Domain.Entities.Team", "FormationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Society.Domain.Entities.ProgramSubject", "ProgramSubject")
                        .WithMany("Teams")
                        .HasForeignKey("ProgramSubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Formation");

                    b.Navigation("ProgramSubject");
                });

            modelBuilder.Entity("Society.Domain.Entities.TeamFormation", b =>
                {
                    b.HasOne("Society.Domain.Entities.ProgramSubject", "ProgramSubject")
                        .WithMany("TeamFormations")
                        .HasForeignKey("ProgramSubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProgramSubject");
                });

            modelBuilder.Entity("Society.Domain.Entities.TeamMember", b =>
                {
                    b.HasOne("Society.Domain.Entities.Team", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Society.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Society.Domain.Entities.User", b =>
                {
                    b.HasOne("Society.Domain.Entities.Person", "Person")
                        .WithOne("User")
                        .HasForeignKey("Society.Domain.Entities.User", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Society.Domain.Entities.UserProfile", b =>
                {
                    b.HasOne("Society.Domain.Entities.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("Society.Domain.Entities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Society.Domain.Entities.Person", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("Society.Domain.Entities.Program", b =>
                {
                    b.Navigation("ProgramSubjects");
                });

            modelBuilder.Entity("Society.Domain.Entities.ProgramSubject", b =>
                {
                    b.Navigation("TeamFormations");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("Society.Domain.Entities.Subject", b =>
                {
                    b.Navigation("ProgramSubjects");
                });

            modelBuilder.Entity("Society.Domain.Entities.Team", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Society.Domain.Entities.TeamFormation", b =>
                {
                    b.Navigation("Team");
                });

            modelBuilder.Entity("Society.Domain.Entities.User", b =>
                {
                    b.Navigation("Profile");
                });
#pragma warning restore 612, 618
        }
    }
}
